/**
 * Copy for the two legal pages, /privacy/ and /terms-of-service/ (rendered by
 * legalRender.ts). These are the URLs submitted to the App Store and Google
 * Play as the privacy policy and terms for every app OOX publishes, so they
 * cover the website, the published games/apps and the studio's services.
 *
 * Kept as code rather than in the admin CMS on purpose: a legal text should
 * change through a reviewed commit, with `updated` bumped in the same change.
 *
 * The ad-network list mirrors the mediation networks declared in
 * public/app-ads.txt — keep the two in step when a network is added or dropped.
 */

export type LegalDoc = {
  /** <h1> and the base of the <title> */
  title: string;
  metaDescription: string;
  /** "Last updated" date, shown under the title */
  updated: string;
  /** body HTML, placed inside the article under the title */
  html: string;
};

const COMPANY = "OOX Limited";
const ADDRESS = "77 Lower Camden Street, Suite 7, Dublin 2, D02 XE80, Ireland";
const REG_NO = "719529";
const EMAIL = "info@ooxlimited.com";
const mail = `<a href="mailto:${EMAIL}">${EMAIL}</a>`;
const ext = (href: string, label: string) =>
  `<a href="${href}" target="_blank" rel="noopener noreferrer">${label}</a>`;

/** Advertising and mediation partners integrated in OOX apps (see app-ads.txt). */
const AD_PARTNERS: [string, string, string][] = [
  ["Google AdMob / Google Ad Manager", "Google Ireland Ltd. / Google LLC", "https://policies.google.com/privacy"],
  ["AppLovin (MAX)", "AppLovin Corporation", "https://www.applovin.com/privacy/"],
  ["Unity Ads / Unity LevelPlay (ironSource)", "Unity Technologies", "https://unity.com/legal/privacy-policy"],
  ["Meta Audience Network", "Meta Platforms Ireland Ltd.", "https://www.facebook.com/privacy/policy/"],
  ["Pangle", "Bytedance Pte. Ltd.", "https://www.pangleglobal.com/privacy/enduser-en"],
  ["Liftoff Monetize (Vungle)", "Liftoff Mobile, Inc.", "https://liftoff.ai/privacy-policy/"],
  ["Chartboost", "Chartboost, Inc.", "https://www.chartboost.com/privacy/"],
  ["InMobi", "InMobi Pte. Ltd.", "https://www.inmobi.com/privacy-policy"],
  ["Digital Turbine (DT Exchange)", "Digital Turbine, Inc.", "https://www.digitalturbine.com/privacy-policy"],
];

const partnerRows = AD_PARTNERS.map(
  ([name, entity, href]) => `<tr><td>${name}</td><td>${entity}</td><td>${ext(href, "Privacy policy")}</td></tr>`,
).join("");

/* ========================================================================== */

export const PRIVACY: LegalDoc = {
  title: "Privacy Policy",
  metaDescription:
    "How OOX Limited collects, uses and protects personal data across its website, mobile games and apps — and the rights you have under the GDPR and other privacy laws.",
  updated: "7 October 2026",
  html: `
<p>This Privacy Policy explains how ${COMPANY} (&ldquo;<strong>OOX</strong>&rdquo;, &ldquo;<strong>we</strong>&rdquo;, &ldquo;<strong>us</strong>&rdquo;) collects, uses, shares and protects personal data when you:</p>
<ul>
  <li>download, install or play any game or use any app we publish on the Apple App Store, Google Play or other platforms (together, the &ldquo;<strong>Apps</strong>&rdquo;);</li>
  <li>visit <a href="/">ooxlimited.com</a> (the &ldquo;<strong>Website</strong>&rdquo;); or</li>
  <li>contact us, subscribe to our newsletter, or work with us as a client or partner.</li>
</ul>
<p>It applies to all of these together (the &ldquo;<strong>Services</strong>&rdquo;). An individual App may show additional information in its store listing or in-app; where it does, that information supplements this policy.</p>

<h2 id="controller">1. Who we are</h2>
<p>The data controller responsible for your personal data is:</p>
<p><strong>${COMPANY}</strong><br>${ADDRESS}<br>Registered in Ireland, company number ${REG_NO}<br>Email: ${mail}</p>
<p>For any privacy question or to exercise your rights, write to ${mail} with &ldquo;Privacy&rdquo; in the subject line.</p>

<h2 id="data-we-collect">2. The data we collect</h2>
<h3>2.1 When you use our Apps</h3>
<p>Our Apps do not require you to create an account, and we do not ask for your name, postal address or phone number to play. We, and the partners listed in section 5, collect the following automatically:</p>
<ul>
  <li><strong>Device identifiers</strong> &ndash; the advertising identifier of your device (Apple IDFA, only if you allow tracking; Google Advertising ID / App Set ID), the identifier for vendors (IDFV), and identifiers generated by the App or our partners&rsquo; SDKs.</li>
  <li><strong>Device and network information</strong> &ndash; device model and manufacturer, operating system and version, language, time zone, screen size, mobile carrier, connection type, and IP address (from which an approximate, country- or city-level location can be derived). We do not collect precise GPS location.</li>
  <li><strong>Usage and gameplay data</strong> &ndash; App version, sessions and session length, levels and progress, in-game events, settings, and the ads you see and interact with.</li>
  <li><strong>Diagnostics</strong> &ndash; crash logs, performance data and error reports.</li>
  <li><strong>Purchase information</strong> &ndash; if you make an in-app purchase, the store confirms the transaction (product, price, currency, transaction ID) to us. Payments are processed entirely by Apple or Google; <strong>we never receive your card or payment details</strong>.</li>
  <li><strong>Consent choices</strong> &ndash; your privacy and tracking choices, so we can respect them.</li>
</ul>

<h3>2.2 When you visit our Website</h3>
<ul>
  <li><strong>Technical data</strong> &ndash; IP address, browser and device type, pages visited, referring page and timestamps, recorded in server logs for security and operation.</li>
  <li><strong>Analytics</strong> &ndash; we use Google Analytics to understand how the Website is used (see section 8 on cookies).</li>
</ul>

<h3>2.3 When you contact us or subscribe</h3>
<ul>
  <li><strong>Contact and support</strong> &ndash; your name, email address, company (if given) and the content of your message, plus any information you choose to send us, such as a device model or a screenshot when reporting a problem with an App.</li>
  <li><strong>Newsletter</strong> &ndash; your email address and your confirmation of the subscription.</li>
  <li><strong>Clients and partners</strong> &ndash; business contact details and the correspondence and project information needed to deliver our services.</li>
</ul>
<p>We do not intentionally collect special categories of personal data (such as health, religious or biometric data). Please do not send it to us.</p>

<h2 id="how-we-use">3. How we use your data and our legal bases</h2>
<p>Under the EU and UK General Data Protection Regulation (&ldquo;<strong>GDPR</strong>&rdquo;) we must have a legal basis for each use of personal data:</p>
<div class="oox-legal__table-wrap"><table>
  <thead><tr><th>Purpose</th><th>Legal basis</th></tr></thead>
  <tbody>
    <tr><td>Providing the Apps and Website, saving your progress, delivering purchased items</td><td>Performance of a contract (our Terms of Service)</td></tr>
    <tr><td>Showing <strong>personalised</strong> ads and measuring ad performance (EEA, UK and Switzerland)</td><td>Your consent, which you can withdraw at any time</td></tr>
    <tr><td>Showing non-personalised (contextual) ads that fund free Apps</td><td>Legitimate interests in offering the Apps free of charge</td></tr>
    <tr><td>Analytics, crash reporting, fixing bugs and improving our games</td><td>Legitimate interests in running and improving our Services; consent where the law requires it for access to your device</td></tr>
    <tr><td>Preventing fraud, cheating, abuse and security incidents</td><td>Legitimate interests in protecting our Services and users</td></tr>
    <tr><td>Answering your messages and providing support</td><td>Legitimate interests, or steps taken at your request before entering into a contract</td></tr>
    <tr><td>Sending our newsletter</td><td>Your consent (double opt-in); you can unsubscribe at any time</td></tr>
    <tr><td>Keeping accounting records, responding to lawful requests, enforcing our rights</td><td>Compliance with legal obligations; legitimate interests</td></tr>
  </tbody>
</table></div>
<p>Where we rely on legitimate interests, we have weighed them against your rights and you may object at any time (section 9). We do not make decisions about you based solely on automated processing that produce legal or similarly significant effects. Ad selection by our partners is automated, but it does not have such effects.</p>

<h2 id="advertising">4. Advertising, consent and tracking</h2>
<p>Many of our Apps are free to play and funded by advertising. Ads are served by the third-party networks listed in section 5, which use device identifiers and the data described above to decide which ads to show, to cap how often you see them, to measure results and to prevent ad fraud.</p>
<ul>
  <li><strong>EEA, UK and Switzerland</strong> &ndash; before any personalised advertising, the App asks for your consent through a consent management platform (Google&rsquo;s User Messaging Platform, which supports the IAB Transparency &amp; Consent Framework). If you decline, you will see only non-personalised ads. You can change your choice at any time from the privacy or settings option in the App, or by deleting and reinstalling it.</li>
  <li><strong>iOS</strong> &ndash; we only access your IDFA if you allow it through Apple&rsquo;s App Tracking Transparency prompt. You can change this anytime under <em>Settings &rsaquo; Privacy &amp; Security &rsaquo; Tracking</em>.</li>
  <li><strong>Android</strong> &ndash; you can delete or reset your advertising ID under <em>Settings &rsaquo; Privacy &rsaquo; Ads</em> (or <em>Settings &rsaquo; Google &rsaquo; Ads</em>).</li>
  <li><strong>United States</strong> &ndash; see section 11 for your right to opt out of targeted advertising.</li>
</ul>

<h2 id="sharing">5. Who we share data with</h2>
<p>We do not sell your personal data for money. We share it only as follows:</p>
<h3>5.1 Advertising and mediation partners</h3>
<p>The networks below may receive the device, usage and advertising data described in section 2.1 from our Apps. Each acts as an independent controller of the data it receives for its own advertising purposes, under its own privacy policy:</p>
<div class="oox-legal__table-wrap"><table>
  <thead><tr><th>Partner</th><th>Company</th><th>More information</th></tr></thead>
  <tbody>${partnerRows}</tbody>
</table></div>
<p>Not every App uses every partner; an App only contains the SDKs it needs.</p>
<h3>5.2 Service providers (processors)</h3>
<p>We use carefully selected providers that process data only on our instructions and under a data-processing agreement, including:</p>
<ul>
  <li><strong>Analytics and crash reporting</strong> &ndash; Google Firebase (Google Analytics for Firebase, Crashlytics) and Unity Analytics, where used in an App (${ext("https://firebase.google.com/support/privacy", "Firebase privacy")});</li>
  <li><strong>Website analytics</strong> &ndash; Google Analytics (${ext("https://policies.google.com/privacy", "Google privacy policy")});</li>
  <li><strong>Email and newsletter</strong> &ndash; Mailchimp (Intuit) (${ext("https://mailchimp.com/legal/privacy/", "Mailchimp privacy")}) and our email provider;</li>
  <li><strong>Hosting and infrastructure</strong> &ndash; the providers that host our Website and back-end services.</li>
</ul>
<h3>5.3 Platforms</h3>
<p>Apple and Google operate the App Store and Google Play and process your purchases and downloads under their own privacy policies.</p>
<h3>5.4 Other disclosures</h3>
<p>We may disclose data where required by law or a valid request from a public authority; to protect the rights, property or safety of OOX, our users or others; or to a buyer or successor if all or part of our business is sold, merged or reorganised. In that case this policy will continue to protect your data.</p>

<h2 id="transfers">6. International transfers</h2>
<p>We are based in Ireland. Some of our partners and providers process data outside the European Economic Area, including in the United States. Where they do, we rely on an adequacy decision of the European Commission (such as the EU-U.S. Data Privacy Framework for certified companies) or on the European Commission&rsquo;s Standard Contractual Clauses, with additional safeguards where needed. You can ask us for more information about these safeguards at ${mail}.</p>

<h2 id="retention">7. How long we keep data</h2>
<ul>
  <li><strong>App analytics and gameplay data</strong> &ndash; up to 26 months from collection, then deleted or anonymised.</li>
  <li><strong>Crash and diagnostic reports</strong> &ndash; up to 90 days.</li>
  <li><strong>Support and contact messages</strong> &ndash; up to 2 years after the conversation ends.</li>
  <li><strong>Newsletter</strong> &ndash; until you unsubscribe.</li>
  <li><strong>Client and accounting records</strong> &ndash; for as long as Irish law requires (generally 6 years).</li>
  <li><strong>Server logs</strong> &ndash; up to 90 days, unless needed to investigate a security incident.</li>
</ul>
<p>Advertising partners keep the data they receive according to their own policies.</p>

<h2 id="cookies">8. Cookies and similar technologies</h2>
<p>The Website uses a small number of cookies. Strictly necessary cookies keep the site working and secure. Google Analytics cookies (<code>_ga</code>, <code>_ga_*</code>, kept for up to 2 years) help us understand how visitors use the site; you can block them in your browser settings or with the ${ext("https://tools.google.com/dlpage/gaoptout", "Google Analytics opt-out add-on")}. Inside the Apps, SDKs use device identifiers and local storage rather than browser cookies, as described in sections 2.1 and 4.</p>

<h2 id="your-rights">9. Your rights</h2>
<p>If you are in the EEA, UK or Switzerland, you have the right to:</p>
<ul>
  <li><strong>access</strong> the personal data we hold about you and receive a copy;</li>
  <li><strong>rectify</strong> inaccurate data;</li>
  <li><strong>erase</strong> your data (&ldquo;right to be forgotten&rdquo;);</li>
  <li><strong>restrict</strong> how we use it;</li>
  <li><strong>data portability</strong> &ndash; receive it in a machine-readable format;</li>
  <li><strong>object</strong> to processing based on legitimate interests, and to direct marketing at any time;</li>
  <li><strong>withdraw consent</strong> at any time, without affecting processing that took place before; and</li>
  <li><strong>complain to a supervisory authority</strong>. Our lead authority is the ${ext("https://www.dataprotection.ie/", "Data Protection Commission")} (21 Fitzwilliam Square South, Dublin 2, D02 RD28, Ireland). You can also complain to the authority where you live or work.</li>
</ul>
<p>To exercise a right, email ${mail}. Because our Apps do not use accounts, please include your App name, platform and, where possible, your device&rsquo;s advertising ID or the in-app user ID shown in the App&rsquo;s settings, so we can find your data. We will reply within one month (extendable by two months for complex requests) and may need to verify your identity. Exercising your rights is free of charge.</p>

<h2 id="data-deletion">10. Deleting your data</h2>
<p>You can have your data deleted at any time:</p>
<ol>
  <li><strong>Request deletion</strong> &ndash; email ${mail} with the subject &ldquo;Data deletion request&rdquo;, naming the App and your platform and including the in-app user ID or advertising ID if you can. We will delete the personal data we hold about you within 30 days and confirm when it is done. Limited records we must keep by law (such as purchase records for tax purposes) are retained only for that purpose and period.</li>
  <li><strong>Stop new collection</strong> &ndash; uninstalling the App stops all data collection from it. You can also reset your advertising ID (section 4) so that past data can no longer be linked to your device.</li>
</ol>
<p>Game progress stored only on your device is deleted when you uninstall the App.</p>

<h2 id="us-residents">11. Additional information for United States residents</h2>
<p>Residents of California and other U.S. states with comprehensive privacy laws (including Colorado, Connecticut, Virginia, Utah, Texas, Oregon and others) have the right to know what personal information we collect, to access, correct and delete it, and not to be discriminated against for exercising these rights.</p>
<p>In the preceding 12 months we have collected the categories of information described in section 2: identifiers (such as device and advertising IDs and IP address), internet or other electronic network activity, approximate geolocation, commercial information (in-app purchase records) and inferences used for advertising. We collect them for the purposes in section 3 and disclose them to the categories of recipients in section 5.</p>
<p>Making device identifiers available to advertising networks for targeted (cross-context behavioural) advertising may be considered a &ldquo;sale&rdquo; or &ldquo;sharing&rdquo; of personal information under these laws. <strong>You can opt out</strong> by enabling &ldquo;Limit Ad Tracking&rdquo; / denying tracking on iOS, deleting your advertising ID on Android, or emailing ${mail} with the subject &ldquo;Do not sell or share my personal information&rdquo;. We honour Global Privacy Control signals on the Website. We do not knowingly sell or share the personal information of consumers under 16. We do not use sensitive personal information to infer characteristics about you.</p>
<p>You may use an authorised agent to make a request; we may ask the agent for proof of authorisation and verify your identity. If we deny your request, you may appeal by replying to our decision.</p>

<h2 id="children">12. Children</h2>
<p>Unless an App&rsquo;s store listing states otherwise, our Apps are intended for a general audience and are not directed at children under 13 (or under 16 in the EEA, where the age of digital consent in Ireland is 16). We do not knowingly collect personal data from children below these ages without verified parental consent.</p>
<p>Where an App is designed for or may appeal to children, we comply with the U.S. Children&rsquo;s Online Privacy Protection Act (COPPA), the GDPR and the Google Play Families Policy and Apple&rsquo;s Kids Category guidelines: we may use an age screen, we treat players identified as children as such, we do not show them personalised advertising, and we only use advertising and analytics SDKs that are certified for, or configured for, child-directed use.</p>
<p>If you believe a child has given us personal data, contact ${mail} and we will delete it.</p>

<h2 id="security">13. Security</h2>
<p>We use appropriate technical and organisational measures to protect personal data, including encryption in transit (HTTPS/TLS), access controls limited to people who need the data, and contracts with our providers. No method of transmission or storage is completely secure, but we work to protect your data and will notify you and the authorities of a breach where the law requires it.</p>

<h2 id="third-party-links">14. Third-party links and services</h2>
<p>Our Services may link to or display content from third parties (for example ads, app stores or social networks). Their handling of your data is governed by their own privacy policies, not this one.</p>

<h2 id="changes">15. Changes to this policy</h2>
<p>We may update this policy from time to time, for example when we add a new App or partner or when the law changes. The &ldquo;Last updated&rdquo; date above shows when it last changed. Where changes are significant, we will give notice in the App or on the Website, and ask for your consent again if the law requires it.</p>

<h2 id="contact">16. Contact us</h2>
<p><strong>${COMPANY}</strong><br>${ADDRESS}<br>Company number ${REG_NO}<br>Email: ${mail}</p>
`,
};

/* ========================================================================== */

export const TERMS: LegalDoc = {
  title: "Terms of Service",
  metaDescription:
    "The terms that apply when you download, play or use any game or app published by OOX Limited, or use the ooxlimited.com website.",
  updated: "7 October 2026",
  html: `
<p>These Terms of Service (the &ldquo;<strong>Terms</strong>&rdquo;) are an agreement between you and ${COMPANY} (&ldquo;<strong>OOX</strong>&rdquo;, &ldquo;<strong>we</strong>&rdquo;, &ldquo;<strong>us</strong>&rdquo;). They govern your use of every game and app we publish on the Apple App Store, Google Play or other platforms (the &ldquo;<strong>Apps</strong>&rdquo;), the website <a href="/">ooxlimited.com</a> (the &ldquo;<strong>Website</strong>&rdquo;), and any related content and features (together, the &ldquo;<strong>Services</strong>&rdquo;).</p>
<p><strong>By downloading, installing, accessing or using the Services you agree to these Terms. If you do not agree, do not use the Services.</strong> Please also read our <a href="/privacy/">Privacy Policy</a>, which explains how we handle personal data.</p>
<p>Game and app development work we carry out for business clients is governed by the separate agreement signed with each client, not by these Terms.</p>

<h2 id="about-us">1. About us</h2>
<p>${COMPANY} is a company registered in Ireland under company number ${REG_NO}, with its registered office at ${ADDRESS}. You can contact us at ${mail}.</p>

<h2 id="eligibility">2. Who can use the Services</h2>
<p>You may use the Services if you are at least 13 years old, or older where the law of your country requires it (16 in some EEA countries), or if a parent or legal guardian has agreed to these Terms on your behalf. If you are under the age of majority where you live, a parent or guardian must review these Terms with you and is responsible for your use of the Services, including any purchases. Some Apps may set a higher minimum age, shown in their store listing.</p>

<h2 id="licence">3. Your licence to use the Apps</h2>
<p>Subject to these Terms, we grant you a personal, limited, non-exclusive, non-transferable, non-sublicensable, revocable licence to download, install and use the Apps on devices you own or control, for your own non-commercial entertainment, as permitted by the usage rules of the store you obtained them from.</p>
<p>The Apps are licensed, not sold. We and our licensors keep all rights, title and interest in the Services, including all software, code, graphics, artwork, characters, music, sound, text, trademarks and the OOX name and logo. Nothing in these Terms transfers any of these rights to you.</p>

<h2 id="acceptable-use">4. Rules of use</h2>
<p>You agree not to, and not to help anyone else to:</p>
<ul>
  <li>copy, modify, distribute, sell, rent, lease or create derivative works of the Services, except as allowed by law;</li>
  <li>decompile, reverse engineer or disassemble the Apps, except to the extent mandatory law expressly permits it;</li>
  <li>use cheats, bots, hacks, mods, exploits, automation or any unauthorised third-party software that interferes with the Services or gives an unfair advantage;</li>
  <li>manipulate, artificially generate or fraudulently click on advertisements, or interfere with our or our partners&rsquo; ad-tracking or measurement;</li>
  <li>buy, sell or trade Virtual Items or accounts outside the Services, or exploit bugs to obtain them;</li>
  <li>attempt to gain unauthorised access to our systems, disrupt or overload the Services, or circumvent any security or technical restriction;</li>
  <li>harass, threaten or abuse others, or upload or share content that is unlawful, infringing, hateful, sexually explicit or otherwise objectionable, where an App allows you to share content; or</li>
  <li>use the Services in breach of any applicable law, including export control and sanctions laws.</li>
</ul>

<h2 id="purchases">5. In-app purchases and virtual items</h2>
<p>Some Apps let you buy virtual currency, items, content, subscriptions or features such as ad removal (&ldquo;<strong>Virtual Items</strong>&rdquo;) with real money, or earn them through play.</p>
<ul>
  <li><strong>Payment.</strong> All purchases are processed by Apple or Google under their terms and refund policies. Prices are shown in the App before you buy and include any applicable VAT or sales tax.</li>
  <li><strong>Nature of Virtual Items.</strong> Virtual Items are a limited licence to use digital content within the App. They have no monetary value, are not property, cannot be exchanged for real money or anything of value, and cannot be transferred between accounts, devices or Apps except where the App expressly supports it.</li>
  <li><strong>Subscriptions.</strong> Where an App offers a subscription, it renews automatically at the end of each period unless you cancel at least 24 hours before renewal in your App Store or Google Play account settings. Deleting the App does not cancel a subscription.</li>
  <li><strong>Right of withdrawal (EEA and UK consumers).</strong> You normally have 14 days to withdraw from a purchase of digital content. By confirming an in-app purchase, you expressly request that the content is supplied immediately and acknowledge that you lose your right of withdrawal once the supply has begun. This does not affect your rights if the content is faulty or not as described.</li>
  <li><strong>Refunds.</strong> Refunds are handled by the store you purchased from (Apple: <a href="https://reportaproblem.apple.com" target="_blank" rel="noopener noreferrer">reportaproblem.apple.com</a>; Google Play: through your order history). If a purchased item was not delivered, contact us at ${mail} with your order number and we will help.</li>
  <li><strong>Changes.</strong> We may change, rebalance or remove Virtual Items as part of operating and improving a game. If we permanently stop offering an App, we will give reasonable advance notice in the App where we can, and paid Virtual Items you have not used will be handled as required by applicable consumer law.</li>
</ul>

<h2 id="advertising">6. Advertising</h2>
<p>Many Apps are free and supported by advertising, which may include rewarded ads you choose to watch in exchange for in-game benefits. Ads are provided by third parties; we are not responsible for third-party products or services advertised in the Apps. How advertising data is used, and your choices about it, are described in our <a href="/privacy/#advertising">Privacy Policy</a>.</p>

<h2 id="user-content">7. Feedback and user content</h2>
<p>If you send us feedback, ideas or suggestions, you agree that we may use them without restriction or compensation to you. If an App lets you create or share content (for example a player name), you keep any rights you have in it but grant us a worldwide, royalty-free licence to host, display and use it as needed to operate the Services. You are responsible for that content, and we may remove content that breaches these Terms.</p>

<h2 id="updates">8. Updates and availability</h2>
<p>We may update the Apps to fix bugs, improve features, meet legal or platform requirements, or add or remove content. Some updates may be required to keep using an App. We aim to keep the Services available, but we do not guarantee that they will be uninterrupted, error-free or available on every device or in every country, and we may suspend or discontinue an App or feature. Where you are a consumer, we will keep the Apps in conformity with these Terms and supply the updates needed for that, as required by law.</p>

<h2 id="third-parties">9. Third-party services</h2>
<p>The Services may include or link to services provided by third parties, such as app stores, ad networks, analytics providers, social networks and websites. Those services are governed by their own terms and privacy policies, and we are not responsible for them.</p>

<h2 id="termination">10. Suspension and termination</h2>
<p>You may stop using the Services at any time by deleting the Apps. We may suspend or end your access to the Services if you seriously or repeatedly breach these Terms, if required by law, or to protect the Services or other players. Where reasonable, we will tell you why and give you a chance to respond. Sections that by their nature should survive termination (including 3, 7 and 11 to 15) continue to apply.</p>

<h2 id="disclaimers">11. Our responsibility to you</h2>
<p>If you are a consumer, you have legal rights in relation to digital content that is faulty or not as described, and <strong>nothing in these Terms affects those statutory rights</strong>. Advice about your legal rights is available from your local consumer advice organisation (in Ireland, the Competition and Consumer Protection Commission).</p>
<p>Apart from those rights, and to the fullest extent permitted by law, the Services are provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, and we do not give any other warranties, express or implied, including fitness for a particular purpose or that the Services will meet your requirements.</p>

<h2 id="liability">12. Limitation of liability</h2>
<p>Nothing in these Terms limits or excludes our liability for death or personal injury caused by our negligence, for fraud or fraudulent misrepresentation, for gross negligence or wilful misconduct, or for any other liability that cannot be limited or excluded under applicable law.</p>
<p>Subject to that, we are not liable for loss or damage that was not reasonably foreseeable, for losses caused by your breach of these Terms, for loss of data stored only on your device, or for business losses (the Apps are for personal, non-commercial use). To the extent permitted by law, our total liability to you for all claims relating to the Services is limited to the greater of (a) the amount you paid us for the Services in the 12 months before the claim and (b) EUR 100.</p>

<h2 id="apple">13. Additional terms for Apps obtained from the Apple App Store</h2>
<p>If you downloaded an App from the Apple App Store, the following also applies, and these Terms are in addition to Apple&rsquo;s ${ext("https://www.apple.com/legal/internet-services/itunes/dev/stdeula/", "Licensed Application End User License Agreement")} where that would otherwise apply:</p>
<ul>
  <li>These Terms are between you and OOX only, not Apple. OOX, not Apple, is solely responsible for the App and its content.</li>
  <li>Your licence is limited to using the App on Apple-branded products you own or control, as permitted by the Usage Rules in the Apple Media Services Terms and Conditions, except that the App may be accessed by other accounts associated with you through Family Sharing.</li>
  <li>Apple has no obligation to provide any maintenance or support for the App.</li>
  <li>If the App fails to conform to any applicable warranty, you may notify Apple and Apple will refund the purchase price (if any) for the App. To the maximum extent permitted by law, Apple has no other warranty obligation with respect to the App, and any other claims, losses or costs attributable to a failure to conform to a warranty are OOX&rsquo;s responsibility.</li>
  <li>OOX, not Apple, is responsible for addressing any claims by you or a third party relating to the App or your use of it, including product liability claims, claims that the App fails to conform to legal or regulatory requirements, and claims under consumer protection, privacy or similar laws.</li>
  <li>If a third party claims that the App or your use of it infringes their intellectual property rights, OOX, not Apple, is solely responsible for the investigation, defence, settlement and discharge of that claim.</li>
  <li>You confirm that you are not located in a country subject to a U.S. Government embargo or designated as a &ldquo;terrorist supporting&rdquo; country, and that you are not on any U.S. Government list of prohibited or restricted parties.</li>
  <li>You must comply with applicable third-party terms (such as your wireless data service agreement) when using the App.</li>
  <li>Apple and its subsidiaries are third-party beneficiaries of these Terms and, once you accept them, Apple will have the right to enforce them against you as a third-party beneficiary.</li>
</ul>
<p>Questions, complaints or claims about an App should be sent to us at ${mail} or ${ADDRESS}.</p>

<h2 id="google">14. Additional terms for Apps obtained from Google Play</h2>
<p>If you downloaded an App from Google Play, your use of it is also subject to the Google Play Terms of Service. Google is not responsible for the App or for providing support for it. If these Terms conflict with the Google Play Terms of Service regarding your use of Google Play, the Google Play Terms of Service apply to that extent.</p>

<h2 id="law">15. Governing law and disputes</h2>
<p>These Terms are governed by the laws of Ireland. The courts of Ireland have jurisdiction over any dispute, except that if you are a consumer living in the EEA, the UK or Switzerland, you also benefit from the mandatory protections of the law of the country where you live, and you may bring proceedings in the courts of that country.</p>
<p>Before starting any proceedings, please contact us at ${mail} so that we can try to resolve the issue informally. Most concerns can be resolved quickly this way.</p>

<h2 id="general">16. General</h2>
<ul>
  <li><strong>Changes to these Terms.</strong> We may update these Terms to reflect changes to the Services, the law or platform rules. The &ldquo;Last updated&rdquo; date shows the latest version. We will give reasonable notice in the App or on the Website of material changes, and continued use after they take effect means you accept them. If you do not agree, you should stop using the Services.</li>
  <li><strong>Entire agreement.</strong> These Terms and our Privacy Policy are the entire agreement between you and us about the Services.</li>
  <li><strong>Severability.</strong> If any part of these Terms is found to be invalid or unenforceable, the rest remains in effect.</li>
  <li><strong>No waiver.</strong> If we do not enforce a right immediately, we can still enforce it later.</li>
  <li><strong>Assignment.</strong> We may transfer our rights and obligations under these Terms to another organisation, for example as part of a sale of our business, and will make sure your rights are not reduced. You may not transfer your rights without our written consent.</li>
  <li><strong>Language.</strong> These Terms are written in English. Any translation is for convenience only; the English version prevails to the extent permitted by law.</li>
</ul>

<h2 id="contact">17. Contact us</h2>
<p><strong>${COMPANY}</strong><br>${ADDRESS}<br>Company number ${REG_NO}<br>Email: ${mail}</p>
`,
};
